name: Test Project
on: workflow_dispatch
jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: action/setup-node@v3
